In [2]:
import numpy as np

Numpy arrays are of 2 types
1. 1d array
2. 2d array

In [5]:
#Creation of 1d arrays

mylist = [1,2,3,4,5]
print(mylist)
type(mylist)

[1, 2, 3, 4, 5]


list

In [6]:
#converting the list into a np array
array1 = np.array(mylist)
array1

array([1, 2, 3, 4, 5])

In [7]:
#to check dimension of array
print(array1.ndim)

1


In [9]:
#Shape of np array
array1.shape

(5,)

In [10]:
#size of array
array1.size

5

In [11]:
#dtype of array
array1.dtype

dtype('int32')

In [14]:
#Creation of 2d array
mylist2 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
array2 = np.array(mylist2)
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
array2.ndim

2

In [16]:
#shape gives no. of rows and columns
array2.shape

(3, 5)

In [17]:
#size gives the number of elemets in array
array2.size

15

# CREATION OF ARRAYS USING ARANGE

In [19]:
np.arange(0,10)
#creates a 1d array starting from 0[inclusive] and 10[exclusive]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#Create an array with step
#even number array
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
#ARRAYS WITH ZEROS
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
#2d array with zeros
np.zeros(shape=(4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#ARRAYS WITH ONES
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones(shape=(4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
#IDENTITY MATRIX - which has diagonal elements are 1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# CREATION OF ARRAYS USING LINSPACE

In [31]:
np.linspace(0,5,10)
#creates a 1d array between 0 and 5
#the third argument --10 represents the number of elements in array
#all elements are evenly spaced between start and stop

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# CREATION OF ARRAYS USING RANDOM

In [34]:
np.random.rand(5)
#generates 5 random elements between 0 and 1.

array([0.12136511, 0.00061467, 0.00268226, 0.11902902, 0.15179803])

In [36]:
np.random.randint(low=1,high=10,size=6)
#creates 1d array with values between 1 and 10

array([9, 4, 8, 5, 5, 8])

In [37]:
np.random.randint(low =1,high=10,size=(4,5))
#creates a 2d array with values between 1 and 10

array([[7, 5, 8, 2, 1],
       [1, 2, 6, 5, 5],
       [1, 5, 3, 6, 7],
       [3, 6, 3, 6, 8]])

# ARRAY OPERATIONS

In [39]:
array3 = np.arange(20)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
#Reshape
#converts 1d array into 2d array using reshape
array3.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
#Max & Min / ArgMax & ArgMin
randarr = np.random.randint(2,100,10)
randarr

array([ 2, 24, 99, 27, 76, 77, 43, 49,  6, 29])

In [44]:
randarr.max()

99

In [45]:
randarr.min()

2

In [46]:
randarr.argmin() #gives the index of minimum element in the array

0

In [47]:
randarr.argmax() #gives the index of max element

2

# Mathematical Operations with Arrays

In [54]:
arr1 = np.arange(0,20)
arr2 = np.arange(100,120)
#we can do these operations as long as both arrays have same size

In [50]:
arr1 + arr2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138])

In [51]:
arr1 * arr2

array([   0,  101,  204,  309,  416,  525,  636,  749,  864,  981, 1100,
       1221, 1344, 1469, 1596, 1725, 1856, 1989, 2124, 2261])

In [52]:
arr1 - arr2

array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
       -100, -100, -100, -100, -100, -100, -100, -100, -100])

In [53]:
arr1 / arr2

array([0.        , 0.00990099, 0.01960784, 0.02912621, 0.03846154,
       0.04761905, 0.05660377, 0.06542056, 0.07407407, 0.08256881,
       0.09090909, 0.0990991 , 0.10714286, 0.11504425, 0.12280702,
       0.13043478, 0.13793103, 0.14529915, 0.15254237, 0.15966387])

In [56]:
#Using scalar values
arr1 + 10 #add 10 to each element


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [58]:
#Square root
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [60]:
#logs
np.log(arr2)

array([4.60517019, 4.61512052, 4.62497281, 4.63472899, 4.6443909 ,
       4.65396035, 4.66343909, 4.67282883, 4.68213123, 4.69134788,
       4.70048037, 4.7095302 , 4.71849887, 4.72738782, 4.73619845,
       4.74493213, 4.75359019, 4.76217393, 4.77068462, 4.77912349])

In [61]:
#trignometric function
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [62]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [64]:
arr = np.random.rand(8)
arr

array([0.33652845, 0.16055269, 0.19495504, 0.14961825, 0.67983748,
       0.60902291, 0.42928047, 0.80108647])

# #Statistical functions

In [65]:
arr.reshape(2,4)

array([[0.33652845, 0.16055269, 0.19495504, 0.14961825],
       [0.67983748, 0.60902291, 0.42928047, 0.80108647]])

In [67]:
#mean
arr.mean()

0.4201102217150175

In [68]:
np.mean(arr)

0.4201102217150175

In [69]:
#finding mean column wise
np.mean(arr.reshape(2,4),axis=0)

array([0.50818297, 0.3847878 , 0.31211776, 0.47535236])

In [70]:
#finding mean row wise
np.mean(arr.reshape(2,4),axis=1)

array([0.21041361, 0.62980683])

In [71]:
#standard deviation
np.std(arr)

0.2362705093456191

In [74]:
#finding standard deviation column wise
np.std(arr.reshape(2,4),axis=0)

array([0.17165451, 0.22423511, 0.11716271, 0.32573411])

In [75]:
#Sum of array
np.sum(arr)

3.36088177372014

In [76]:
#sum row wise
np.sum(arr.reshape(2,4),axis= 0)

array([1.01636593, 0.7695756 , 0.62423552, 0.95070472])

In [78]:
#Sum column wise
np.sum(arr.reshape(2,4),axis = 1)

array([0.84165444, 2.51922733])

# Array Indexing

In [79]:
#1d array indexing and slicing

In [81]:
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
arr1[7]

17

In [85]:
arr1[1:7]

array([11, 12, 13, 14, 15, 16])

In [86]:
arr1[:6]

array([10, 11, 12, 13, 14, 15])

In [87]:
arr1[3:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
arr1[:-1]#everything except last element

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [90]:
#reversing the whole array
arr1[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [98]:
#2d array indexing and slicing
twod_arr = np.array([[5,10,15,20],[6,12,18,24],[7,14,21,28]])
twod_arr

array([[ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28]])

In [99]:
twod_arr.shape

(3, 4)

In [100]:
#extracting the element
twod_arr[0,0]

5

In [103]:
twod_arr[0]

array([ 5, 10, 15, 20])

In [101]:
twod_arr[1,1]

12

In [104]:
#SLICING in 2d array
#slicing(start row : stoprow : steprow, startcol:stopcol:stepcol)

In [106]:
twod_arr[0:2,1:3] #0th row to 2nd row and 1st col to 3rd col

array([[10, 15],
       [12, 18]])

In [109]:
#extracting a column
twod_arr[:,0]

array([5, 6, 7])

In [111]:
twod_arr[0:3,0]

array([5, 6, 7])

# Conditional Slicing

In [112]:
arr2 = np.arange(0,15)
arr2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
checkarr = arr2 > 5
checkarr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [115]:
arr2[checkarr] #array of elements greater than 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [116]:
arr2[arr2>10]

array([11, 12, 13, 14])

# JOINING ARRAYS
#use concatenate function
arr1 = np.arange(0,5)
arr2 = np.arange(2,7)

In [121]:
np.concatenate((arr1, arr2) )

array([0, 1, 2, 3, 4, 2, 3, 4, 5, 6])

In [122]:
twod_arr1 = np.array([[5,10,15,20],[6,12,18,24],[7,14,21,28]])
twod_arr2 = np.array([[15,120,150,201],[62,120,178,274],[17,144,251,238]])

#join at the columns
np.concatenate((twod_arr1,twod_arr2) , axis = 1)

array([[  5,  10,  15,  20,  15, 120, 150, 201],
       [  6,  12,  18,  24,  62, 120, 178, 274],
       [  7,  14,  21,  28,  17, 144, 251, 238]])

In [123]:
#join at the rows
np.concatenate((twod_arr1,twod_arr2) , axis = 0)

array([[  5,  10,  15,  20],
       [  6,  12,  18,  24],
       [  7,  14,  21,  28],
       [ 15, 120, 150, 201],
       [ 62, 120, 178, 274],
       [ 17, 144, 251, 238]])