# Random Forest Classification
Random Forest algorithm is a supervised algorithm. As the name suggest , this algorithm creates the forest with a number of trees.

topmost application of Random forest is the motion gaming.

# Working of Random Forest Algorithm

1. Assume number of cases in the training set is N, Then the sample of N cases is taken at random but with replacement. This sample will be the training set for growing the tree.

2. If there are M input variables, a number m < M is specified such that at each node, m variables are selected at random out of the M. The best split on these m is used to split the node. The value m is held constant while we grow the forest, three possible values for m : 1/2M, sqrt(M) , 2*sqrt(M)

3. Each tree is grown to the largest extent possible. Predict new data by aggregating the prediction of the ntree trees(i.e majority votes for classification, average for regression.)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("https://s3.amazonaws.com/thinkific/file_uploads/287654/attachments/2e3/a35/b45/Social_Network_Ads.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
df.drop('User ID',axis=1,inplace=True)
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [8]:
df=pd.get_dummies(df,drop_first=True)

In [9]:
cols = ['Age','EstimatedSalary','Gender_Male','Purchased']
df= df[cols]
df

Age  EstimatedSalary  Gender_Male  Purchased
0     19            19000            1          0
1     35            20000            1          0
2     26            43000            0          0
3     27            57000            0          0
4     19            76000            1          0
..   ...              ...          ...        ...
395   46            41000            0          1
396   51            23000            1          1
397   50            20000            0          1
398   36            33000            1          0
399   49            36000            0          1

[400 rows x 4 columns]

In [12]:
X = df.iloc[:,:-1].values
X.shape

(400, 3)

In [14]:
Y = df.iloc[:,-1].values
Y.shape

(400,)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [22]:
X_train

array([[    44,  39000,      0],
       [    32, 120000,      1],
       [    38,  50000,      0],
       [    32, 135000,      0],
       [    52,  21000,      0],
       [    53, 104000,      0],
       [    39,  42000,      1],
       [    38,  61000,      1],
       [    36,  50000,      0],
       [    36,  63000,      0],
       [    35,  25000,      0],
       [    35,  50000,      1],
       [    42,  73000,      1],
       [    47,  49000,      0],
       [    59,  29000,      0],
       [    49,  65000,      1],
       [    45, 131000,      0],
       [    31,  89000,      0],
       [    46,  82000,      0],
       [    47,  51000,      0],
       [    26,  15000,      1],
       [    60, 102000,      1],
       [    38, 112000,      0],
       [    40, 107000,      1],
       [    42,  53000,      0],
       [    35,  59000,      1],
       [    48,  41000,      1],
       [    48, 134000,      0],
       [    38, 113000,      0],
       [    29, 148000,      1],
       [  

In [24]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train =sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [26]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators = 10, n_jobs =2 , random_state=0)
#n_estimators = number of decision trees, n_jobs = number of computers.
clf.fit(X_train , Y_train)

RandomForestClassifier(n_estimators=10, n_jobs=2, random_state=0)

In [28]:
Y_pred = clf.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [29]:
Y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [30]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [31]:
cm = confusion_matrix(Y_test , Y_pred)

In [32]:
cm

array([[64,  4],
       [ 3, 29]], dtype=int64)

In [33]:
metrics.accuracy_score(Y_test, Y_pred)
#ACCURACY

0.93